name: Generate Client

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  generate-client:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.15"
          enable-cache: true
      - name: Install dependencies
        run: npm ci
        working-directory: frontend
      - run: uv sync
        working-directory: backend
      - run: uv run bash scripts/generate-client.sh
        env:
          VIRTUAL_ENV: backend/.venv
      - name: Add changes to git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git add frontend/src/client
      - name: Push changes
        run: |
          git diff --staged --quiet || (git commit -m "✨ Autogenerate frontend client" && git push)
